### ISSUE TITLE
Set up development environment and tools

### ISSUE THREAD

**Issue by chrislom12** [COS301-SE-2023/Domain-Pulse-A-Sentiment-Analysis-Platform#13]
- [x] Set up commands that will be used for serving/building
- [ ] Set up testing environment, to validate code pre-deployment

**Comment by cadendobson** [comment]
can't setup testing env yet because we still need more virtual machines

**Comment by chrislom12** [comment]
Understood, the issue will still remain in backlog till we have finished it in a later iteration
